### ISSUE TITLE
Obtain Kane and Will County TIF districts

### ISSUE THREAD

**Issue by stevevance** [ChicagoCityscape/website#353]
## Kane County
Kane County has some TIF districts, with boundaries stored on ArcGIS, through a proxy.

http://gistech.countyofkane.org/DotNet2/proxy.ashx?http://gistech.countyofkane.org/arcgis/rest/services/KaneCOC_TIF/MapServer/0/

Here's how you get them from that server:

````
esri2geojson --proxy "http://gistech.countyofkane.org/DotNet2/proxy.ashx?" http://gistech.countyofkane.org/arcgis/rest/services/KaneCOC_TIF/MapServer/0/ filename.geojson
````

Replace "filename" with the right filename. Then do the GIS magic to convert this to EPSG/SRID `3435`. 

## Will County
https://rest.willcountyillinois.com/arcgis/rest/services/TaxingDistrictsMapLayers/MapServer/9

**Comment by stevevance** [comment]
@calvinbrown32 Please spot check that the data includes actual TIF districts. 

For example, here's the [Fox River TIF (# 3)](http://www.geneva.il.us/720/TIF-District-3) in Geneva, Kane County, IL, that started in 2016.

**Comment by stevevance** [comment]
It looks like the Kane County GIS only has Geneva TIF 2, which you can see when we [filter Maps Explorer](https://www.chicagocityscape.com/maps/index.php#/?type=tif&place=municipality-geneva).

@calvinbrown32 Can you find or make the geometry for TIF 3?

**Comment by calvinbrown32** [comment]
Oh no! How did you figure out the TIF was missing? I can’t find a gis file anywhere. 
I can draw it based on the online report, but I’m worried about precision. What do you suggest?
I had terrible food poisoning Friday evening, and it ate up almost my entire weekend :(

**Comment by stevevance** [comment]
@calvinbrown32 I couldn't find it in a GIF file, either, so can you please draw it? Does the online report have a list of PINs?

If it has a list of PINs then you can [download the Kane County parcels](https://www.dropbox.com/s/sfl1jsndwsdd1yn/kane_parcels_20180206.gpkg.zip?dl=0) from my Dropbox and use those to help with the precision.
