### ISSUE TITLE
API isn't returning Boundaries property

### ISSUE THREAD

**Issue by stevevance** [ChicagoCityscape/website#438]
https://www.chicagocityscape.com/api/index.php?pin=&lat=41.878951&lng=-87.660603&address=1329%20W%20Adams%20St&city=Chicago&key=null

**Comment by ryantimjohn** [comment]
Hi Steve, any word on this? Let me know if there's anyway can help with the fix.

**Comment by ryantimjohn** [comment]
Hey Steve, following up on this. Any word?

**Comment by stevevance** [comment]
I'm working on this today. It should be fixed by the end of the day.

**Comment by ryantimjohn** [comment]
Thanks, Steve!

**Comment by stevevance** [comment]
Try it now!
